"""change post body

Revision ID: 67db5aae6087
Revises: 00d56d4b984c
Create Date: 2024-01-26 16:33:54.855584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67db5aae6087'
down_revision = '00d56d4b984c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_body')
        batch_op.create_index(batch_op.f('ix_post_body'), ['body'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_body'))
        batch_op.create_index('ix_post_body', ['body'], unique=1)

    # ### end Alembic commands ###
